# OSEMN Exercises

In [3]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [26]:
nums = str(np.random.rand(1, 10).tolist())

simple_data = open("simple_data.txt", "w")
simple_data.write(nums)

with open("simple_data.txt", mode='r') as file:
    #print(file.read())
    for line in file:
        print(line)

[[0.631951794903728, 0.4053439095041217, 0.7764772464836199, 0.8725760106932633, 0.48076520345862117, 0.014618726891835188, 0.25269517016402954, 0.4117916974503547, 0.7309787382216788, 0.008997099269288933]]


2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [36]:
matrix = str(np.random.rand(5, 5))

data = open("data.txt", "w")
data.write(matrix)

with open("data.txt", mode='r') as file:
    print(file.read())

[[0.30946007 0.61928701 0.45471533 0.67742666 0.79705252]
 [0.20775138 0.84541612 0.2031521  0.77940304 0.84339174]
 [0.00487514 0.17237422 0.7957159  0.09363101 0.27577317]
 [0.48556363 0.8837576  0.24112456 0.72180731 0.16604715]
 [0.16579532 0.28890761 0.20426058 0.25234937 0.80630909]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [26]:
import csv

with open("data.txt", mode='r+') as file:
    lines = []
    for line in file:
        line = line.replace(' [', '[')
        line = line.replace('[', '')
        line = line.replace(']]', '')
        line = line.replace(']', ',')
        line = line.replace('  ', ',')
        line = line.replace(' ', ',')

        print('Line: ', line)

        lines += line.split(",")

while '\n' in lines:
    lines.remove('\n')

lines = [[x] for x in lines]

print(lines)


    

with open("data.csv", 'r+') as file_csv:
    writer = csv.writer(file_csv)
    writer.writerows(lines)
    for line in csv.reader(file_csv, delimiter=','):
        print(line)


Line:  0.30946007,0.61928701,0.45471533,0.67742666,0.79705252,

Line:  0.20775138,0.84541612,0.2031521,0.77940304,0.84339174,

Line:  0.00487514,0.17237422,0.7957159,0.09363101,0.27577317,

Line:  0.48556363,0.8837576,0.24112456,0.72180731,0.16604715,

Line:  0.16579532,0.28890761,0.20426058,0.25234937,0.80630909
[['0.30946007'], ['0.61928701'], ['0.45471533'], ['0.67742666'], ['0.79705252'], ['0.20775138'], ['0.84541612'], ['0.2031521'], ['0.77940304'], ['0.84339174'], ['0.00487514'], ['0.17237422'], ['0.7957159'], ['0.09363101'], ['0.27577317'], ['0.48556363'], ['0.8837576'], ['0.24112456'], ['0.72180731'], ['0.16604715'], ['0.16579532'], ['0.28890761'], ['0.20426058'], ['0.25234937'], ['0.80630909']]
['0.30946007']
[]
['0.61928701']
[]
['0.45471533']
[]
['0.67742666']
[]
['0.79705252']
[]
['0.20775138']
[]
['0.84541612']
[]
['0.2031521']
[]
['0.77940304']
[]
['0.84339174']
[]
['0.00487514']
[]
['0.17237422']
[]
['0.7957159']
[]
['0.09363101']
[]
['0.27577317']
[]
['0.48556363']
[]
[

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.